#!/bin/sh

MODPROBE=/sbin/modprobe
RETVAL=0

load_from_file() {

	grep '^[^#]' "${1}" | \
	while read module args; do
		[ "$module" ] || continue
		if ${MODPROBE} $module $args; then
			echo "  $module loaded"
		else
			echo "  $module failed"
		fi
	done

}

start() {
	
	echo -n "Probing modules: "
	if [ ! -x "${MODPROBE}" -o ! -f "/etc/modules" ]; then
		echo "missing"
		exit 1
	else
		echo
	fi
	
	if [ -d /etc/modules-load.d ]; then
		load_from_file /etc/modules
		for file in /etc/modules-load.d/*
		do
			load_from_file $file
		done
	fi
}


stop() {
	echo "Nothing to do"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	status)
		status $processname
		RETVAL=$?
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|status|restart}"
		;;
esac
exit $RETVAL
